slice_range: [5,25]
# slice_range: [20,120]

num_input_slices : 1
imgSize: 256
filters: 32
## basic setting
device: "cuda"
epochs: 50
batch_size: 2
lr: 0.001
## resume train
resume_training: 0
load_cp: 0
## number workers
train_num_workers: 0
val_num_workers: 0
## tensorboard
tb_write_loss: 1
tb_write_image: 1
## save options
save_step: 5
testDC: 0
###################################loss weights#############################
alpha: 0.5
beta: 0.6
advWeight: 0.5
ssimWeight: 1

################################## paths ###################################

imageDataDir : "E:/FastMRI/miniBatch/"                                                                                                                             ## the path of the train datas that used
mask_path: "D:/datas/masks/radial/radial_30.pickle" 
tb_dir: "./tensorboard/radial30/"
output_dir: "./checkPoint/radial30/"

predModelPath: "E:/DLCode/DLFastReconModel/MANET/checkPoint/radial30/Best_CP_epoch.pth"
predictDir: "E:/FastMRI/test"