slice_range: [5,25]
# slice_range: [20,120]
isZeroToOne: 1
num_input_slices : 1
imgSize: 256
filters: 32
## basic setting
device: "cuda"
epochs: 50
batch_size: 2
lr: 0.0001
weight_clip: 0.01
## resume train
resume_training: 0
load_cp: 0
## number workers
train_num_workers: 0
val_num_workers: 0
## tensorboard
tb_write_loss: 1
tb_write_image: 1
## save options
save_step: 5
testDC: 0
###################################loss weights#############################
alpha: 0.6
beta: 0.6
rate: 100
advWeight: 0.1
ssimWeight: 1
critic: 9
################################## paths ###################################

imageDataDir : "E:/FastMRI/miniBatch/"                                                                                                                             ## the path of the train datas that used
mask_path: "D:/datas/masks/radial/radial_30.pickle" 
tb_dir: "./tensorboard/directModal/radial30"
output_dir: "./checkPoint/directModal/radial30"

predModelPath: "./NetworkResult/MultiModal/gaussian20/Best_PSNR_epoch.pth"
predictResultPath: "./NetworkResult/MultiModal/gaussian20/"
predictDir: "E:/FastMRI/test"
visualize_images: 1