input_channel : 1
output_channel : 1
num_filters : 64
lr: 0.0001
loss_weights: [1, 200, 10, 10]                                   # Loss weighting [Imspac L2, Imspace L1, Kspace L2, GAN_Loss]. Losses are weighted to be roughly at the same scale.
slice_range : [20,120]
minmax_noise_val: [-0.01, 0.01]
bilinear : 0
ispool : 0
num_input_slices : 1

imgSize : 256
lrStep : 10
lrgamma : 0.5
device : "cuda:0"

imageDataDir: "D:/datas/IXI-1-save/"
output_dir : "E:/DLCode/DLFastReconstruction/ESSGAN/checkpoints/test11223344/"
tb_dir : "E:/DLCode/DLFastReconstruction/ESSGAN/tb/test11223344/" 
mask_path: "D:/datas/masks/radial/radial_30.npy"


predModelPath : "E:/DLCode/DLFastReconstruction/ESSGAN/checkpoints/test11223344/Best_CP_epoch.pth"
predictDir : "D:/datas/IXI-T1-save/test/IXI503-Guys-1021-T1.hdf5"
predictResultPath : "E:/DLCode/DLFastReconstruction/ESSGAN/predict/IXI/test/"
predResultName : "predResult_essgan_test.hdf5"


isTrain : 1
stopPatience : 10
batch_size : 4
train_num_workers : 0
val_num_workers : 0
val_percent : 0.2
tb_write_loss : 1
tb_write_image : 1


epochs : 500
GAN_training : 1
save_step : 5

savePredication : 1
visualize_images: 1

fMapNum : 64